language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      env: DEPLOY_FILE=cimgui.so
      compiler: clang
      script: sudo apt-get install wx-common; cmake ./CMakeLists.txt; make
    - os: osx
      env: DEPLOY_FILE=cimgui.dylib
      compiler: clang
      script: cmake ./CMakeLists.txt; make
