language: cpp

addons:
  apt:
    packages:
      - libwxgtk3.0-dev

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      env: DEPLOY_FILE=cimgui.so
      compiler: clang
      script: cmake ./CMakeLists.txt; make
    - os: osx
      env: DEPLOY_FILE=cimgui.dylib
      compiler: clang
      script: cmake ./CMakeLists.txt; make
