language: cpp

addons:
  apt:
    packages:
      - libwxgtk3.0-dev
      - libtinyxml-dev
      - libopenal-dev
      - libglew-dev
      - libfreetype6-dev

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      env: DEPLOY_FILE=./lib/libNewton.so
      compiler: gcc
      script: cmake ./CMakeLists.txt; make
    - os: osx
      env: DEPLOY_FILE=./lib/libNewton.so
      compiler: gcc
      script: cmake ./CMakeLists.txt; make

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install tinyxml; fi

deploy:
  provider: releases
  api_key:
    secure: mqKl2V96UO84/c6bSs0gEsNTn8CMDeNt79pC2HkZ4BsvaA49Qfu7AZmajamEl5I4LZOD0Zf5YoKUkjtV/6X8nbbqVB2sPkvkVWBGqAnWi02pyKK88BU8r9hXl0kUyzhe8Qh4kUvAAZWXv5xca2ODZ6o4Jn2Oucz4/GEy22lahyT61l9r3eHRkX34OquULlkSn3THm9DHLks7rGTpLMK3wuBdXkXwklMSgLgxJk3qYy2Jk8/yMRb7c3jfG6J09eGcjPIHok5C1gJt9s0LhdanbbbhyX9cCMtCygUS0YCrDUl1QKrEZ8eoagfQLmaOhuQI4QmFpVa7flL7EUw66m9wTQHLZolBq9PpGxAb3vHfNMIDhCX7cnZNIFGjTYOEsADlM0hETRgwlMsjkpFCev4RzJLO2slLRnCxlewqJz1gVpRi+0vHiAW9igFrA/IrPK8MmjyFgwevQpU34Y6KJujn4eXpcbQCfxRWR91rvz2hT9WNrAnHtMQgQ695PsTtfWf2eZzXuc2aMuTEm4VnpqJsxUh+YKoED1mKXNNDd6pnWpaBVD8IzNKL0sOIKvQqdCuWxQgsRuqfWZ12bmYMd0cAnwn8l23wgo/Gnb/tP2extT8KUM+8GS7SEm68P+A4XrWg4e0xvqhbbIsK3bDaYbhquAqd98Kaiv6XJlDfOmB9FFM=
  skip_cleanup: true
  file: $DEPLOY_FILE
  on:
    tags: true
