clone_folder: c:\projects\newton
os: Visual Studio 2015
configuration: Release
skip_tags: true

before_build:
  - cd c:\projects\newton\
  - cmake

platform:
  - x64
    
build:
    project: c:\projects\newton\coreLibrary_300/projects/windows/project_vs2015_dll/newton.vcxproj

after_build:
  - copy .\coreLibrary_300\projects\windows\project_vs2015_dll\x64\newton\Release\newton.dll .\newton$(PLATFORM).dll

artifacts:
  - path: .\newton$(PLATFORM).dll
    name: theDLL
    type: File

deploy:
  release: newton-v$(appveyor_build_version)-$(PLATFORM)
  description: 'Appveyor Build'
  provider: GitHub
  auth_token:
    secure: XSb9h9W4f7bSSB7IQ3m3wngD2WA/hS0mq/aEDynzsVGkETjkjgq8im67ByH7FDX3
  artifact: theDLL
  draft: false
  prerelease: false
  on:
    branch: master
