clone_folder: c:\projects\libsoil
os: Visual Studio 2015
configuration: Release

skip_tags: true

before_build:
  - cmake -G "Visual Studio 14 2015 Win64"

platform:
  - Win32
  - x64
    
build:
    project: c:\projects\libsoil\projects\win\ALL_BUILD.vcxproj
