clone_folder: c:\projects\newton
os: Visual Studio 2015
configuration: Release
skip_tags: true

before_build:
  - cd c:\projects\newton\
  - cmake

platform:
  - x64
    
build:
    project: c:\projects\newton\coreLibrary_300/projects/windows/project_vs2015_dll/newton.vcxproj
